#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alllive.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AllliveDB")]
	public partial class AllliveDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertpassword(password instance);
    partial void Updatepassword(password instance);
    partial void Deletepassword(password instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertSchedule(Schedule instance);
    partial void UpdateSchedule(Schedule instance);
    partial void DeleteSchedule(Schedule instance);
    partial void InsertScheduleMeeting(ScheduleMeeting instance);
    partial void UpdateScheduleMeeting(ScheduleMeeting instance);
    partial void DeleteScheduleMeeting(ScheduleMeeting instance);
    partial void InsertTutorProfile(TutorProfile instance);
    partial void UpdateTutorProfile(TutorProfile instance);
    partial void DeleteTutorProfile(TutorProfile instance);
    #endregion
		
		public AllliveDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AllliveDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AllliveDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllliveDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllliveDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllliveDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<password> passwords
		{
			get
			{
				return this.GetTable<password>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<SearchTutor> SearchTutors
		{
			get
			{
				return this.GetTable<SearchTutor>();
			}
		}
		
		public System.Data.Linq.Table<Schedule> Schedules
		{
			get
			{
				return this.GetTable<Schedule>();
			}
		}
		
		public System.Data.Linq.Table<ScheduleMeeting> ScheduleMeetings
		{
			get
			{
				return this.GetTable<ScheduleMeeting>();
			}
		}
		
		public System.Data.Linq.Table<TutorProfile> TutorProfiles
		{
			get
			{
				return this.GetTable<TutorProfile>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertregistereduser")]
		public int insertregistereduser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(255)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="VarChar(255)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(16)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, lastName, firstName, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertscheduledmeeting")]
		public int insertscheduledmeeting(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionName", DbType="VarChar(100)")] string sessionName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(250)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="Date")] System.Nullable<System.DateTime> date, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="Time")] System.Nullable<System.TimeSpan> startTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTime", DbType="Time")] System.Nullable<System.TimeSpan> endTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeZone", DbType="NVarChar(7)")] string timeZone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Recurr", DbType="Bit")] System.Nullable<bool> recurr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Frequency", DbType="Int")] System.Nullable<int> frequency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatDaily", DbType="Int")] System.Nullable<int> repeatDaily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatWeekly", DbType="Int")] System.Nullable<int> repeatWeekly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthly", DbType="Int")] System.Nullable<int> repeatMonthly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sunday", DbType="Bit")] System.Nullable<bool> sunday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monday", DbType="Bit")] System.Nullable<bool> monday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tuesday", DbType="Bit")] System.Nullable<bool> tuesday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wednesday", DbType="Bit")] System.Nullable<bool> wednesday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thursday", DbType="Bit")] System.Nullable<bool> thursday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Friday", DbType="Bit")] System.Nullable<bool> friday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Saturday", DbType="Bit")] System.Nullable<bool> saturday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthRadio1", DbType="Bit")] System.Nullable<bool> repeatMonthRadio1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthRadio2", DbType="Bit")] System.Nullable<bool> repeatMonthRadio2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Radio2List1", DbType="Int")] System.Nullable<int> radio2List1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Radio2List2", DbType="Int")] System.Nullable<int> radio2List2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDateBy", DbType="Date")] System.Nullable<System.DateTime> endDateBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDateAfter", DbType="Int")] System.Nullable<int> endDateAfter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MeetingLink", DbType="VarChar(200)")] string meetingLink)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionName, description, date, startTime, endTime, timeZone, recurr, frequency, repeatDaily, repeatWeekly, repeatMonthly, sunday, monday, tuesday, wednesday, thursday, friday, saturday, repeatMonthRadio1, repeatMonthRadio2, radio2List1, radio2List2, endDateBy, endDateAfter, userID, meetingLink);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserSchedule")]
		public ISingleResult<UserScheduleResult> UserSchedule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((ISingleResult<UserScheduleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CancelMeeting")]
		public int CancelMeeting([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="Int")] System.Nullable<int> sessionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditMeeting")]
		public int EditMeeting(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="Int")] System.Nullable<int> sessionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionName", DbType="VarChar(100)")] string sessionName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(250)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="Date")] System.Nullable<System.DateTime> date, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTime", DbType="Time")] System.Nullable<System.TimeSpan> startTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTime", DbType="Time")] System.Nullable<System.TimeSpan> endTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeZone", DbType="NVarChar(7)")] string timeZone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Recurr", DbType="Bit")] System.Nullable<bool> recurr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Frequency", DbType="Int")] System.Nullable<int> frequency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatDaily", DbType="Int")] System.Nullable<int> repeatDaily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatWeekly", DbType="Int")] System.Nullable<int> repeatWeekly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthly", DbType="Int")] System.Nullable<int> repeatMonthly, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sunday", DbType="Bit")] System.Nullable<bool> sunday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monday", DbType="Bit")] System.Nullable<bool> monday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tuesday", DbType="Bit")] System.Nullable<bool> tuesday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wednesday", DbType="Bit")] System.Nullable<bool> wednesday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thursday", DbType="Bit")] System.Nullable<bool> thursday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Friday", DbType="Bit")] System.Nullable<bool> friday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Saturday", DbType="Bit")] System.Nullable<bool> saturday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthRadio1", DbType="Bit")] System.Nullable<bool> repeatMonthRadio1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RepeatMonthRadio2", DbType="Bit")] System.Nullable<bool> repeatMonthRadio2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Radio2List1", DbType="Int")] System.Nullable<int> radio2List1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Radio2List2", DbType="Int")] System.Nullable<int> radio2List2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDateBy", DbType="Date")] System.Nullable<System.DateTime> endDateBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDateAfter", DbType="Int")] System.Nullable<int> endDateAfter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MeetingLink", DbType="VarChar(200)")] string meetingLink)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionID, sessionName, description, date, startTime, endTime, timeZone, recurr, frequency, repeatDaily, repeatWeekly, repeatMonthly, sunday, monday, tuesday, wednesday, thursday, friday, saturday, repeatMonthRadio1, repeatMonthRadio2, radio2List1, radio2List2, endDateBy, endDateAfter, meetingLink);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.password")]
	public partial class password : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _passwordID;
		
		private string _password1;
		
		private System.Nullable<int> _UserID;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpasswordIDChanging(int value);
    partial void OnpasswordIDChanged();
    partial void Onpassword1Changing(string value);
    partial void Onpassword1Changed();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public password()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int passwordID
		{
			get
			{
				return this._passwordID;
			}
			set
			{
				if ((this._passwordID != value))
				{
					this.OnpasswordIDChanging(value);
					this.SendPropertyChanging();
					this._passwordID = value;
					this.SendPropertyChanged("passwordID");
					this.OnpasswordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="password", Storage="_password1", DbType="VarChar(16)")]
		public string password1
		{
			get
			{
				return this._password1;
			}
			set
			{
				if ((this._password1 != value))
				{
					this.Onpassword1Changing(value);
					this.SendPropertyChanging();
					this._password1 = value;
					this.SendPropertyChanged("password1");
					this.Onpassword1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_password", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.passwords.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.passwords.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _LastName;
		
		private string _FirstName;
		
		private EntitySet<password> _passwords;
		
		private EntitySet<Schedule> _Schedules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    #endregion
		
		public User()
		{
			this._passwords = new EntitySet<password>(new Action<password>(this.attach_passwords), new Action<password>(this.detach_passwords));
			this._Schedules = new EntitySet<Schedule>(new Action<Schedule>(this.attach_Schedules), new Action<Schedule>(this.detach_Schedules));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(255)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(255)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_password", Storage="_passwords", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<password> passwords
		{
			get
			{
				return this._passwords;
			}
			set
			{
				this._passwords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Schedule", Storage="_Schedules", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Schedule> Schedules
		{
			get
			{
				return this._Schedules;
			}
			set
			{
				this._Schedules.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_passwords(password entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_passwords(password entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Schedules(Schedule entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Schedules(Schedule entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SearchTutor")]
	public partial class SearchTutor
	{
		
		private string _SearchText;
		
		private int _HourlyRate;
		
		private bool _Sunday;
		
		private bool _Monday;
		
		private bool _Tuesday;
		
		private bool _Wednesday;
		
		private bool _Thursday;
		
		private bool _Friday;
		
		private bool _Saturday;
		
		private int _StudentLevel;
		
		public SearchTutor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchText", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SearchText
		{
			get
			{
				return this._SearchText;
			}
			set
			{
				if ((this._SearchText != value))
				{
					this._SearchText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HourlyRate", DbType="Int NOT NULL")]
		public int HourlyRate
		{
			get
			{
				return this._HourlyRate;
			}
			set
			{
				if ((this._HourlyRate != value))
				{
					this._HourlyRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="Bit NOT NULL")]
		public bool Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this._Sunday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Bit NOT NULL")]
		public bool Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Bit NOT NULL")]
		public bool Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this._Tuesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Bit NOT NULL")]
		public bool Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this._Wednesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Bit NOT NULL")]
		public bool Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this._Thursday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Bit NOT NULL")]
		public bool Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="Bit NOT NULL")]
		public bool Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this._Saturday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLevel", DbType="Int NOT NULL")]
		public int StudentLevel
		{
			get
			{
				return this._StudentLevel;
			}
			set
			{
				if ((this._StudentLevel != value))
				{
					this._StudentLevel = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schedule")]
	public partial class Schedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SessionID;
		
		private int _UserID;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSessionIDChanging(int value);
    partial void OnSessionIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public Schedule()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this.OnSessionIDChanging(value);
					this.SendPropertyChanging();
					this._SessionID = value;
					this.SendPropertyChanged("SessionID");
					this.OnSessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Schedule", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Schedules.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Schedules.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ScheduleMeeting")]
	public partial class ScheduleMeeting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SessionID;
		
		private string _SessionName;
		
		private string _Description;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _StartTime;
		
		private System.TimeSpan _EndTime;
		
		private string _TimeZone;
		
		private bool _Recurr;
		
		private int _Frequency;
		
		private int _RepeatDaily;
		
		private int _RepeatWeekly;
		
		private int _RepeatMonthly;
		
		private bool _Sunday;
		
		private bool _Monday;
		
		private bool _Tuesday;
		
		private bool _Wednesday;
		
		private bool _Thursday;
		
		private bool _Friday;
		
		private bool _Saturday;
		
		private bool _RepeatMonthRadio1;
		
		private bool _RepeatMonthRadio2;
		
		private int _Radio2List1;
		
		private int _Radio2List2;
		
		private System.DateTime _EndDateBy;
		
		private int _EndDateAfter;
		
		private string _MeetingLink;
		
		private string _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSessionIDChanging(int value);
    partial void OnSessionIDChanged();
    partial void OnSessionNameChanging(string value);
    partial void OnSessionNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnStartTimeChanging(System.TimeSpan value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.TimeSpan value);
    partial void OnEndTimeChanged();
    partial void OnTimeZoneChanging(string value);
    partial void OnTimeZoneChanged();
    partial void OnRecurrChanging(bool value);
    partial void OnRecurrChanged();
    partial void OnFrequencyChanging(int value);
    partial void OnFrequencyChanged();
    partial void OnRepeatDailyChanging(int value);
    partial void OnRepeatDailyChanged();
    partial void OnRepeatWeeklyChanging(int value);
    partial void OnRepeatWeeklyChanged();
    partial void OnRepeatMonthlyChanging(int value);
    partial void OnRepeatMonthlyChanged();
    partial void OnSundayChanging(bool value);
    partial void OnSundayChanged();
    partial void OnMondayChanging(bool value);
    partial void OnMondayChanged();
    partial void OnTuesdayChanging(bool value);
    partial void OnTuesdayChanged();
    partial void OnWednesdayChanging(bool value);
    partial void OnWednesdayChanged();
    partial void OnThursdayChanging(bool value);
    partial void OnThursdayChanged();
    partial void OnFridayChanging(bool value);
    partial void OnFridayChanged();
    partial void OnSaturdayChanging(bool value);
    partial void OnSaturdayChanged();
    partial void OnRepeatMonthRadio1Changing(bool value);
    partial void OnRepeatMonthRadio1Changed();
    partial void OnRepeatMonthRadio2Changing(bool value);
    partial void OnRepeatMonthRadio2Changed();
    partial void OnRadio2List1Changing(int value);
    partial void OnRadio2List1Changed();
    partial void OnRadio2List2Changing(int value);
    partial void OnRadio2List2Changed();
    partial void OnEndDateByChanging(System.DateTime value);
    partial void OnEndDateByChanged();
    partial void OnEndDateAfterChanging(int value);
    partial void OnEndDateAfterChanged();
    partial void OnMeetingLinkChanging(string value);
    partial void OnMeetingLinkChanged();
    partial void OnActiveChanging(string value);
    partial void OnActiveChanged();
    #endregion
		
		public ScheduleMeeting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this.OnSessionIDChanging(value);
					this.SendPropertyChanging();
					this._SessionID = value;
					this.SendPropertyChanged("SessionID");
					this.OnSessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SessionName
		{
			get
			{
				return this._SessionName;
			}
			set
			{
				if ((this._SessionName != value))
				{
					this.OnSessionNameChanging(value);
					this.SendPropertyChanging();
					this._SessionName = value;
					this.SendPropertyChanged("SessionName");
					this.OnSessionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="Time NOT NULL")]
		public System.TimeSpan StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="Time NOT NULL")]
		public System.TimeSpan EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this.OnTimeZoneChanging(value);
					this.SendPropertyChanging();
					this._TimeZone = value;
					this.SendPropertyChanged("TimeZone");
					this.OnTimeZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recurr", DbType="Bit NOT NULL")]
		public bool Recurr
		{
			get
			{
				return this._Recurr;
			}
			set
			{
				if ((this._Recurr != value))
				{
					this.OnRecurrChanging(value);
					this.SendPropertyChanging();
					this._Recurr = value;
					this.SendPropertyChanged("Recurr");
					this.OnRecurrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="Int NOT NULL")]
		public int Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this.OnFrequencyChanging(value);
					this.SendPropertyChanging();
					this._Frequency = value;
					this.SendPropertyChanged("Frequency");
					this.OnFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatDaily", DbType="Int NOT NULL")]
		public int RepeatDaily
		{
			get
			{
				return this._RepeatDaily;
			}
			set
			{
				if ((this._RepeatDaily != value))
				{
					this.OnRepeatDailyChanging(value);
					this.SendPropertyChanging();
					this._RepeatDaily = value;
					this.SendPropertyChanged("RepeatDaily");
					this.OnRepeatDailyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatWeekly", DbType="Int NOT NULL")]
		public int RepeatWeekly
		{
			get
			{
				return this._RepeatWeekly;
			}
			set
			{
				if ((this._RepeatWeekly != value))
				{
					this.OnRepeatWeeklyChanging(value);
					this.SendPropertyChanging();
					this._RepeatWeekly = value;
					this.SendPropertyChanged("RepeatWeekly");
					this.OnRepeatWeeklyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthly", DbType="Int NOT NULL")]
		public int RepeatMonthly
		{
			get
			{
				return this._RepeatMonthly;
			}
			set
			{
				if ((this._RepeatMonthly != value))
				{
					this.OnRepeatMonthlyChanging(value);
					this.SendPropertyChanging();
					this._RepeatMonthly = value;
					this.SendPropertyChanged("RepeatMonthly");
					this.OnRepeatMonthlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="Bit NOT NULL")]
		public bool Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this.OnSundayChanging(value);
					this.SendPropertyChanging();
					this._Sunday = value;
					this.SendPropertyChanged("Sunday");
					this.OnSundayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Bit NOT NULL")]
		public bool Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this.OnMondayChanging(value);
					this.SendPropertyChanging();
					this._Monday = value;
					this.SendPropertyChanged("Monday");
					this.OnMondayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Bit NOT NULL")]
		public bool Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this.OnTuesdayChanging(value);
					this.SendPropertyChanging();
					this._Tuesday = value;
					this.SendPropertyChanged("Tuesday");
					this.OnTuesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Bit NOT NULL")]
		public bool Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this.OnWednesdayChanging(value);
					this.SendPropertyChanging();
					this._Wednesday = value;
					this.SendPropertyChanged("Wednesday");
					this.OnWednesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Bit NOT NULL")]
		public bool Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this.OnThursdayChanging(value);
					this.SendPropertyChanging();
					this._Thursday = value;
					this.SendPropertyChanged("Thursday");
					this.OnThursdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Bit NOT NULL")]
		public bool Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this.OnFridayChanging(value);
					this.SendPropertyChanging();
					this._Friday = value;
					this.SendPropertyChanged("Friday");
					this.OnFridayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="Bit NOT NULL")]
		public bool Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this.OnSaturdayChanging(value);
					this.SendPropertyChanging();
					this._Saturday = value;
					this.SendPropertyChanged("Saturday");
					this.OnSaturdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthRadio1", DbType="Bit NOT NULL")]
		public bool RepeatMonthRadio1
		{
			get
			{
				return this._RepeatMonthRadio1;
			}
			set
			{
				if ((this._RepeatMonthRadio1 != value))
				{
					this.OnRepeatMonthRadio1Changing(value);
					this.SendPropertyChanging();
					this._RepeatMonthRadio1 = value;
					this.SendPropertyChanged("RepeatMonthRadio1");
					this.OnRepeatMonthRadio1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthRadio2", DbType="Bit NOT NULL")]
		public bool RepeatMonthRadio2
		{
			get
			{
				return this._RepeatMonthRadio2;
			}
			set
			{
				if ((this._RepeatMonthRadio2 != value))
				{
					this.OnRepeatMonthRadio2Changing(value);
					this.SendPropertyChanging();
					this._RepeatMonthRadio2 = value;
					this.SendPropertyChanged("RepeatMonthRadio2");
					this.OnRepeatMonthRadio2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radio2List1", DbType="Int NOT NULL")]
		public int Radio2List1
		{
			get
			{
				return this._Radio2List1;
			}
			set
			{
				if ((this._Radio2List1 != value))
				{
					this.OnRadio2List1Changing(value);
					this.SendPropertyChanging();
					this._Radio2List1 = value;
					this.SendPropertyChanged("Radio2List1");
					this.OnRadio2List1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radio2List2", DbType="Int NOT NULL")]
		public int Radio2List2
		{
			get
			{
				return this._Radio2List2;
			}
			set
			{
				if ((this._Radio2List2 != value))
				{
					this.OnRadio2List2Changing(value);
					this.SendPropertyChanging();
					this._Radio2List2 = value;
					this.SendPropertyChanged("Radio2List2");
					this.OnRadio2List2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateBy", DbType="Date NOT NULL")]
		public System.DateTime EndDateBy
		{
			get
			{
				return this._EndDateBy;
			}
			set
			{
				if ((this._EndDateBy != value))
				{
					this.OnEndDateByChanging(value);
					this.SendPropertyChanging();
					this._EndDateBy = value;
					this.SendPropertyChanged("EndDateBy");
					this.OnEndDateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateAfter", DbType="Int NOT NULL")]
		public int EndDateAfter
		{
			get
			{
				return this._EndDateAfter;
			}
			set
			{
				if ((this._EndDateAfter != value))
				{
					this.OnEndDateAfterChanging(value);
					this.SendPropertyChanging();
					this._EndDateAfter = value;
					this.SendPropertyChanged("EndDateAfter");
					this.OnEndDateAfterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeetingLink", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string MeetingLink
		{
			get
			{
				return this._MeetingLink;
			}
			set
			{
				if ((this._MeetingLink != value))
				{
					this.OnMeetingLinkChanging(value);
					this.SendPropertyChanging();
					this._MeetingLink = value;
					this.SendPropertyChanged("MeetingLink");
					this.OnMeetingLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TutorProfile")]
	public partial class TutorProfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TutorProfileID;
		
		private int _UserID;
		
		private string _Bio;
		
		private double _Rate;
		
		private bool _Sunday;
		
		private bool _Monday;
		
		private bool _Tuesday;
		
		private bool _Wednesday;
		
		private bool _Thursday;
		
		private bool _Friday;
		
		private bool _Saturday;
		
		private string _StudentLevel;
		
		private bool _Math;
		
		private bool _Reading;
		
		private bool _Science;
		
		private string _Photo;
		
		private string _SundayStart;
		
		private string _SundayEnd;
		
		private string _MondayStart;
		
		private string _MondayEnd;
		
		private string _TuesdayStart;
		
		private string _TuesdayEnd;
		
		private string _WednesdayStart;
		
		private string _WednesdayEnd;
		
		private string _ThursdayStart;
		
		private string _ThursdayEnd;
		
		private string _FridayStart;
		
		private string _FridayEnd;
		
		private string _SaturdayStart;
		
		private string _SaturdayEnd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTutorProfileIDChanging(int value);
    partial void OnTutorProfileIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnBioChanging(string value);
    partial void OnBioChanged();
    partial void OnRateChanging(double value);
    partial void OnRateChanged();
    partial void OnSundayChanging(bool value);
    partial void OnSundayChanged();
    partial void OnMondayChanging(bool value);
    partial void OnMondayChanged();
    partial void OnTuesdayChanging(bool value);
    partial void OnTuesdayChanged();
    partial void OnWednesdayChanging(bool value);
    partial void OnWednesdayChanged();
    partial void OnThursdayChanging(bool value);
    partial void OnThursdayChanged();
    partial void OnFridayChanging(bool value);
    partial void OnFridayChanged();
    partial void OnSaturdayChanging(bool value);
    partial void OnSaturdayChanged();
    partial void OnStudentLevelChanging(string value);
    partial void OnStudentLevelChanged();
    partial void OnMathChanging(bool value);
    partial void OnMathChanged();
    partial void OnReadingChanging(bool value);
    partial void OnReadingChanged();
    partial void OnScienceChanging(bool value);
    partial void OnScienceChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnSundayStartChanging(string value);
    partial void OnSundayStartChanged();
    partial void OnSundayEndChanging(string value);
    partial void OnSundayEndChanged();
    partial void OnMondayStartChanging(string value);
    partial void OnMondayStartChanged();
    partial void OnMondayEndChanging(string value);
    partial void OnMondayEndChanged();
    partial void OnTuesdayStartChanging(string value);
    partial void OnTuesdayStartChanged();
    partial void OnTuesdayEndChanging(string value);
    partial void OnTuesdayEndChanged();
    partial void OnWednesdayStartChanging(string value);
    partial void OnWednesdayStartChanged();
    partial void OnWednesdayEndChanging(string value);
    partial void OnWednesdayEndChanged();
    partial void OnThursdayStartChanging(string value);
    partial void OnThursdayStartChanged();
    partial void OnThursdayEndChanging(string value);
    partial void OnThursdayEndChanged();
    partial void OnFridayStartChanging(string value);
    partial void OnFridayStartChanged();
    partial void OnFridayEndChanging(string value);
    partial void OnFridayEndChanged();
    partial void OnSaturdayStartChanging(string value);
    partial void OnSaturdayStartChanged();
    partial void OnSaturdayEndChanging(string value);
    partial void OnSaturdayEndChanged();
    #endregion
		
		public TutorProfile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TutorProfileID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TutorProfileID
		{
			get
			{
				return this._TutorProfileID;
			}
			set
			{
				if ((this._TutorProfileID != value))
				{
					this.OnTutorProfileIDChanging(value);
					this.SendPropertyChanging();
					this._TutorProfileID = value;
					this.SendPropertyChanged("TutorProfileID");
					this.OnTutorProfileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bio", DbType="VarChar(MAX)")]
		public string Bio
		{
			get
			{
				return this._Bio;
			}
			set
			{
				if ((this._Bio != value))
				{
					this.OnBioChanging(value);
					this.SendPropertyChanging();
					this._Bio = value;
					this.SendPropertyChanged("Bio");
					this.OnBioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Float NOT NULL")]
		public double Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="Bit NOT NULL")]
		public bool Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this.OnSundayChanging(value);
					this.SendPropertyChanging();
					this._Sunday = value;
					this.SendPropertyChanged("Sunday");
					this.OnSundayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Bit NOT NULL")]
		public bool Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this.OnMondayChanging(value);
					this.SendPropertyChanging();
					this._Monday = value;
					this.SendPropertyChanged("Monday");
					this.OnMondayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Bit NOT NULL")]
		public bool Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this.OnTuesdayChanging(value);
					this.SendPropertyChanging();
					this._Tuesday = value;
					this.SendPropertyChanged("Tuesday");
					this.OnTuesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Bit NOT NULL")]
		public bool Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this.OnWednesdayChanging(value);
					this.SendPropertyChanging();
					this._Wednesday = value;
					this.SendPropertyChanged("Wednesday");
					this.OnWednesdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Bit NOT NULL")]
		public bool Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this.OnThursdayChanging(value);
					this.SendPropertyChanging();
					this._Thursday = value;
					this.SendPropertyChanged("Thursday");
					this.OnThursdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Bit NOT NULL")]
		public bool Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this.OnFridayChanging(value);
					this.SendPropertyChanging();
					this._Friday = value;
					this.SendPropertyChanged("Friday");
					this.OnFridayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="Bit NOT NULL")]
		public bool Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this.OnSaturdayChanging(value);
					this.SendPropertyChanging();
					this._Saturday = value;
					this.SendPropertyChanged("Saturday");
					this.OnSaturdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLevel", DbType="NVarChar(20)")]
		public string StudentLevel
		{
			get
			{
				return this._StudentLevel;
			}
			set
			{
				if ((this._StudentLevel != value))
				{
					this.OnStudentLevelChanging(value);
					this.SendPropertyChanging();
					this._StudentLevel = value;
					this.SendPropertyChanged("StudentLevel");
					this.OnStudentLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math", DbType="Bit NOT NULL")]
		public bool Math
		{
			get
			{
				return this._Math;
			}
			set
			{
				if ((this._Math != value))
				{
					this.OnMathChanging(value);
					this.SendPropertyChanging();
					this._Math = value;
					this.SendPropertyChanged("Math");
					this.OnMathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reading", DbType="Bit NOT NULL")]
		public bool Reading
		{
			get
			{
				return this._Reading;
			}
			set
			{
				if ((this._Reading != value))
				{
					this.OnReadingChanging(value);
					this.SendPropertyChanging();
					this._Reading = value;
					this.SendPropertyChanged("Reading");
					this.OnReadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Science", DbType="Bit NOT NULL")]
		public bool Science
		{
			get
			{
				return this._Science;
			}
			set
			{
				if ((this._Science != value))
				{
					this.OnScienceChanging(value);
					this.SendPropertyChanging();
					this._Science = value;
					this.SendPropertyChanged("Science");
					this.OnScienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(255)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SundayStart", DbType="NVarChar(20)")]
		public string SundayStart
		{
			get
			{
				return this._SundayStart;
			}
			set
			{
				if ((this._SundayStart != value))
				{
					this.OnSundayStartChanging(value);
					this.SendPropertyChanging();
					this._SundayStart = value;
					this.SendPropertyChanged("SundayStart");
					this.OnSundayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SundayEnd", DbType="NVarChar(20)")]
		public string SundayEnd
		{
			get
			{
				return this._SundayEnd;
			}
			set
			{
				if ((this._SundayEnd != value))
				{
					this.OnSundayEndChanging(value);
					this.SendPropertyChanging();
					this._SundayEnd = value;
					this.SendPropertyChanged("SundayEnd");
					this.OnSundayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayStart", DbType="NVarChar(20)")]
		public string MondayStart
		{
			get
			{
				return this._MondayStart;
			}
			set
			{
				if ((this._MondayStart != value))
				{
					this.OnMondayStartChanging(value);
					this.SendPropertyChanging();
					this._MondayStart = value;
					this.SendPropertyChanged("MondayStart");
					this.OnMondayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayEnd", DbType="NVarChar(20)")]
		public string MondayEnd
		{
			get
			{
				return this._MondayEnd;
			}
			set
			{
				if ((this._MondayEnd != value))
				{
					this.OnMondayEndChanging(value);
					this.SendPropertyChanging();
					this._MondayEnd = value;
					this.SendPropertyChanged("MondayEnd");
					this.OnMondayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayStart", DbType="NVarChar(20)")]
		public string TuesdayStart
		{
			get
			{
				return this._TuesdayStart;
			}
			set
			{
				if ((this._TuesdayStart != value))
				{
					this.OnTuesdayStartChanging(value);
					this.SendPropertyChanging();
					this._TuesdayStart = value;
					this.SendPropertyChanged("TuesdayStart");
					this.OnTuesdayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayEnd", DbType="NVarChar(20)")]
		public string TuesdayEnd
		{
			get
			{
				return this._TuesdayEnd;
			}
			set
			{
				if ((this._TuesdayEnd != value))
				{
					this.OnTuesdayEndChanging(value);
					this.SendPropertyChanging();
					this._TuesdayEnd = value;
					this.SendPropertyChanged("TuesdayEnd");
					this.OnTuesdayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayStart", DbType="NVarChar(20)")]
		public string WednesdayStart
		{
			get
			{
				return this._WednesdayStart;
			}
			set
			{
				if ((this._WednesdayStart != value))
				{
					this.OnWednesdayStartChanging(value);
					this.SendPropertyChanging();
					this._WednesdayStart = value;
					this.SendPropertyChanged("WednesdayStart");
					this.OnWednesdayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayEnd", DbType="NVarChar(20)")]
		public string WednesdayEnd
		{
			get
			{
				return this._WednesdayEnd;
			}
			set
			{
				if ((this._WednesdayEnd != value))
				{
					this.OnWednesdayEndChanging(value);
					this.SendPropertyChanging();
					this._WednesdayEnd = value;
					this.SendPropertyChanged("WednesdayEnd");
					this.OnWednesdayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayStart", DbType="NVarChar(20)")]
		public string ThursdayStart
		{
			get
			{
				return this._ThursdayStart;
			}
			set
			{
				if ((this._ThursdayStart != value))
				{
					this.OnThursdayStartChanging(value);
					this.SendPropertyChanging();
					this._ThursdayStart = value;
					this.SendPropertyChanged("ThursdayStart");
					this.OnThursdayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayEnd", DbType="NVarChar(20)")]
		public string ThursdayEnd
		{
			get
			{
				return this._ThursdayEnd;
			}
			set
			{
				if ((this._ThursdayEnd != value))
				{
					this.OnThursdayEndChanging(value);
					this.SendPropertyChanging();
					this._ThursdayEnd = value;
					this.SendPropertyChanged("ThursdayEnd");
					this.OnThursdayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayStart", DbType="NVarChar(20)")]
		public string FridayStart
		{
			get
			{
				return this._FridayStart;
			}
			set
			{
				if ((this._FridayStart != value))
				{
					this.OnFridayStartChanging(value);
					this.SendPropertyChanging();
					this._FridayStart = value;
					this.SendPropertyChanged("FridayStart");
					this.OnFridayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayEnd", DbType="NVarChar(20)")]
		public string FridayEnd
		{
			get
			{
				return this._FridayEnd;
			}
			set
			{
				if ((this._FridayEnd != value))
				{
					this.OnFridayEndChanging(value);
					this.SendPropertyChanging();
					this._FridayEnd = value;
					this.SendPropertyChanged("FridayEnd");
					this.OnFridayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaturdayStart", DbType="NVarChar(20)")]
		public string SaturdayStart
		{
			get
			{
				return this._SaturdayStart;
			}
			set
			{
				if ((this._SaturdayStart != value))
				{
					this.OnSaturdayStartChanging(value);
					this.SendPropertyChanging();
					this._SaturdayStart = value;
					this.SendPropertyChanged("SaturdayStart");
					this.OnSaturdayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaturdayEnd", DbType="NVarChar(20)")]
		public string SaturdayEnd
		{
			get
			{
				return this._SaturdayEnd;
			}
			set
			{
				if ((this._SaturdayEnd != value))
				{
					this.OnSaturdayEndChanging(value);
					this.SendPropertyChanging();
					this._SaturdayEnd = value;
					this.SendPropertyChanged("SaturdayEnd");
					this.OnSaturdayEndChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class UserScheduleResult
	{
		
		private int _UserID;
		
		private int _SessionID;
		
		private string _SessionName;
		
		private string _Description;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _StartTime;
		
		private System.TimeSpan _EndTime;
		
		private string _TimeZone;
		
		private bool _Recurr;
		
		private int _Frequency;
		
		private int _RepeatDaily;
		
		private int _RepeatWeekly;
		
		private int _RepeatMonthly;
		
		private bool _Sunday;
		
		private bool _Monday;
		
		private bool _Tuesday;
		
		private bool _Wednesday;
		
		private bool _Thursday;
		
		private bool _Friday;
		
		private bool _Saturday;
		
		private bool _RepeatMonthRadio1;
		
		private bool _RepeatMonthRadio2;
		
		private int _Radio2List1;
		
		private int _Radio2List2;
		
		private System.DateTime _EndDateBy;
		
		private int _EndDateAfter;
		
		private string _MeetingLink;
		
		public UserScheduleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="Int NOT NULL")]
		public int SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this._SessionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SessionName
		{
			get
			{
				return this._SessionName;
			}
			set
			{
				if ((this._SessionName != value))
				{
					this._SessionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="Time NOT NULL")]
		public System.TimeSpan StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this._StartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="Time NOT NULL")]
		public System.TimeSpan EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this._EndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recurr", DbType="Bit NOT NULL")]
		public bool Recurr
		{
			get
			{
				return this._Recurr;
			}
			set
			{
				if ((this._Recurr != value))
				{
					this._Recurr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency", DbType="Int NOT NULL")]
		public int Frequency
		{
			get
			{
				return this._Frequency;
			}
			set
			{
				if ((this._Frequency != value))
				{
					this._Frequency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatDaily", DbType="Int NOT NULL")]
		public int RepeatDaily
		{
			get
			{
				return this._RepeatDaily;
			}
			set
			{
				if ((this._RepeatDaily != value))
				{
					this._RepeatDaily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatWeekly", DbType="Int NOT NULL")]
		public int RepeatWeekly
		{
			get
			{
				return this._RepeatWeekly;
			}
			set
			{
				if ((this._RepeatWeekly != value))
				{
					this._RepeatWeekly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthly", DbType="Int NOT NULL")]
		public int RepeatMonthly
		{
			get
			{
				return this._RepeatMonthly;
			}
			set
			{
				if ((this._RepeatMonthly != value))
				{
					this._RepeatMonthly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="Bit NOT NULL")]
		public bool Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this._Sunday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Bit NOT NULL")]
		public bool Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Bit NOT NULL")]
		public bool Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this._Tuesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Bit NOT NULL")]
		public bool Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this._Wednesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Bit NOT NULL")]
		public bool Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this._Thursday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Bit NOT NULL")]
		public bool Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="Bit NOT NULL")]
		public bool Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this._Saturday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthRadio1", DbType="Bit NOT NULL")]
		public bool RepeatMonthRadio1
		{
			get
			{
				return this._RepeatMonthRadio1;
			}
			set
			{
				if ((this._RepeatMonthRadio1 != value))
				{
					this._RepeatMonthRadio1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatMonthRadio2", DbType="Bit NOT NULL")]
		public bool RepeatMonthRadio2
		{
			get
			{
				return this._RepeatMonthRadio2;
			}
			set
			{
				if ((this._RepeatMonthRadio2 != value))
				{
					this._RepeatMonthRadio2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radio2List1", DbType="Int NOT NULL")]
		public int Radio2List1
		{
			get
			{
				return this._Radio2List1;
			}
			set
			{
				if ((this._Radio2List1 != value))
				{
					this._Radio2List1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radio2List2", DbType="Int NOT NULL")]
		public int Radio2List2
		{
			get
			{
				return this._Radio2List2;
			}
			set
			{
				if ((this._Radio2List2 != value))
				{
					this._Radio2List2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateBy", DbType="Date NOT NULL")]
		public System.DateTime EndDateBy
		{
			get
			{
				return this._EndDateBy;
			}
			set
			{
				if ((this._EndDateBy != value))
				{
					this._EndDateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateAfter", DbType="Int NOT NULL")]
		public int EndDateAfter
		{
			get
			{
				return this._EndDateAfter;
			}
			set
			{
				if ((this._EndDateAfter != value))
				{
					this._EndDateAfter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeetingLink", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string MeetingLink
		{
			get
			{
				return this._MeetingLink;
			}
			set
			{
				if ((this._MeetingLink != value))
				{
					this._MeetingLink = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
