//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alllive.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ScheduleMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleMeeting()
        {
            this.Attendees = new HashSet<Attendee>();
        }
    
        public int SessionID { get; set; }
        [Required(ErrorMessage ="Session Name is Required")]
        public string SessionName { get; set; }
        public string Description { get; set; }
        [Required]
        public System.DateTime Date { get; set; }

        [RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Invalid Time.")]
        public System.DateTime StartTime { get; set; }
        [RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Invalid Time.")]
        public System.DateTime EndTime { get; set; }
        public string TimeZone { get; set; }
        public bool Recurr { get; set; }
        public int Frequency { get; set; }
        public int RepeatDaily { get; set; }
        public int RepeatWeekly { get; set; }
        public int RepeatMonthly { get; set; }
        public int RepeatMonthlyDate { get; set; }
        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool RepeatMonthRadio1 { get; set; }
        public bool RepeatMonthRadio2 { get; set; }
        public int Radio2List1 { get; set; }
        public int Radio2List2 { get; set; }
        public System.DateTime EndDateBy { get; set; }
        public int EndDateAfter { get; set; }
        public string MeetingLink { get; set; }
        public string Active { get; set; }
        public Nullable<int> HostUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendee> Attendees { get; set; }
    }
}
