//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alllive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorProfile
    {
        public int TutorProfileID { get; set; }
        public int UserID { get; set; }
        public string Bio { get; set; }
        public double Rate { get; set; }
        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public string StudentLevel { get; set; }
        public bool Math { get; set; }
        public bool Reading { get; set; }
        public bool Science { get; set; }
        public string Photo { get; set; }
        public string SundayStart { get; set; }
        public string SundayEnd { get; set; }
        public string MondayStart { get; set; }
        public string MondayEnd { get; set; }
        public string TuesdayStart { get; set; }
        public string TuesdayEnd { get; set; }
        public string WednesdayStart { get; set; }
        public string WednesdayEnd { get; set; }
        public string ThursdayStart { get; set; }
        public string ThursdayEnd { get; set; }
        public string FridayStart { get; set; }
        public string FridayEnd { get; set; }
        public string SaturdayStart { get; set; }
        public string SaturdayEnd { get; set; }
        public string HeadLine { get; set; }
        public Nullable<int> ImageID { get; set; }
    }
}
